name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - archspec=0.2.2=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - binutils_impl_linux-64=2.40=hf600244_0
  - blas=1.0=mkl
  - blosc=1.21.5=h0f2a231_0
  - boltons=23.1.1=pyhd8ed1ab_0
  - bottleneck=1.3.7=py311h1f0f07a_1
  - brotli-python=1.1.0=py311hb755f60_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.26.0=hd590300_0
  - ca-certificates=2023.11.17=hbcca054_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2023.11.17=pyhd8ed1ab_0
  - cffi=1.16.0=py311hb3a22ac_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - conda=23.11.0=py311h38be061_1
  - conda-libmamba-solver=24.1.0=pyhd8ed1ab_0
  - conda-package-handling=2.2.0=pyh38be061_0
  - conda-package-streaming=0.9.0=pyhd8ed1ab_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - eccodes=2.33.0=he84ddb8_0
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - fftw=3.3.10=nompi_hc118613_108
  - findlibs=0.0.5=pyhd8ed1ab_0
  - fmt=10.2.1=h00ab1b0_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freeglut=3.2.2=hac7e632_2
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=7.5.0=habd7529_20
  - gdbm=1.18=h0a1914f_2
  - gettext=0.21.1=h27087fc_0
  - git-delta=0.16.5=h2ca70b0_0
  - graphite2=1.3.13=h58526e2_1001
  - harfbuzz=8.3.0=h3d44ed6_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.3=nompi_h4f84152_100
  - icu=73.2=h59595ed_0
  - idna=3.6=pyhd8ed1ab_0
  - ipython=8.12.2=py311h06a4308_0
  - jasper=4.1.2=he6dfbbe_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_0
  - jsonpointer=2.4=py311h38be061_3
  - kernel-headers_linux-64=2.6.32=he073ed8_16
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.2=h659d440_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libaec=1.1.2=h59595ed_1
  - libarchive=3.7.2=h2aa1ff5_1
  - libcurl=8.5.0=hca28451_0
  - libdeflate=1.19=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-devel_linux-64=7.5.0=hda03d7c_20
  - libgcc-ng=13.2.0=h807b86a_4
  - libgfortran-ng=13.2.0=h69a702a_4
  - libgfortran5=13.2.0=ha4646dd_4
  - libglib=2.78.3=h783c2da_0
  - libglu=9.0.0=hac7e632_1003
  - libgomp=13.2.0=h807b86a_4
  - libhwloc=2.9.3=default_h554bfaf_1009
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - libmamba=1.5.6=had39da4_0
  - libmambapy=1.5.6=py311hf2555c7_0
  - libnetcdf=4.9.2=nompi_h9612171_113
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libpng=1.6.39=h753d276_0
  - libsolv=0.7.27=hfc55251_0
  - libsqlite=3.44.2=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_4
  - libtiff=4.6.0=ha9c0a0a_2
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.4=h232c23b_1
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=17.0.6=h4dfa4b3_0
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=h516909a_1000
  - magics-metview-batch=4.15.0=hd93a360_0
  - menuinst=2.0.2=py311h38be061_0
  - metview-batch=5.19.2=h9ce0283_0
  - mkl=2023.2.0=h84fe81f_50496
  - mkl_random=1.2.4=py311hdb19cb5_0
  - ncurses=6.4=h59595ed_2
  - numexpr=2.8.7=py311h65dcdc2_0
  - openssl=3.2.1=hd590300_0
  - packaging=23.2=pyhd8ed1ab_0
  - pango=1.50.14=ha41ecd1_2
  - pcre2=10.42=hcad00b1_0
  - perl=5.32.1=7_hd590300_perl5
  - perl-app-cpanminus=1.7047=pl5321hd8ed1ab_0
  - pip=23.3.2=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - proj=9.3.1=h1d62c97_0
  - psutil=5.9.0=py311h5eee18b_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py311h459d7ec_0
  - python=3.11.4=hab00c5b_0_cpython
  - python-eccodes=1.6.1=py311h1f0f07a_1
  - python_abi=3.11=4_cp311
  - pytz=2023.4=pyhd8ed1ab_0
  - readline=8.2=h8228510_1
  - reproc=14.2.4.post0=hd590300_1
  - reproc-cpp=14.2.4.post0=h59595ed_1
  - requests=2.31.0=pyhd8ed1ab_0
  - ruamel.yaml=0.17.21=py311h5eee18b_0
  - setuptools=69.0.3=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=h9fff704_0
  - sqlite=3.44.2=h2c6b66d_0
  - sysroot_linux-64=2.12=he073ed8_16
  - tbb=2021.11.0=h00ab1b0_1
  - tk=8.6.13=noxft_h4845f30_101
  - urllib3=2.2.0=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml-cpp=0.8.0=h59595ed_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - adbc-driver-manager==0.9.0
      - adbc-driver-sqlite==0.9.0
      - alabaster==0.7.13
      - annotated-types==0.6.0
      - argcomplete==3.1.1
      - astral==3.2
      - babel==2.12.1
      - beautifulsoup4==4.12.2
      - click==8.1.7
      - click-default-group==1.2.4
      - click-default-group-wheel==1.2.2
      - cloudpickle==3.0.0
      - colorcet==3.0.1
      - connectorx==0.3.2
      - contourpy==1.2.0
      - distro==1.8.0
      - docopt==0.6.2
      - docutils==0.20.1
      - fsspec==2023.12.2
      - funcy==2.0
      - funkify==0.4.5
      - geopolars==0.1.0a4
      - gevent==23.9.1
      - greenlet==3.0.3
      - hypothesis==6.98.2
      - iniconfig==2.0.0
      - intel-openmp==2024.1.2
      - jinja2==3.1.2
      - matplotlib-inline==0.1.7
      - numpy==1.26.4
      - pandas==2.2.2
      - pdbufr==0.11.0
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pipdeptree==2.21.0
      - platformdirs==3.10.0
      - plbufr==0.1.dev329+g4b7cae2.d20240526
      - pluggy==1.5.0
      - polars==0.20.7
      - prompt-toolkit==3.0.46
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==16.1.0
      - pycparser==2.22
      - pygments==2.18.0
      - pytest==8.2.1
      - pytest-metadata==3.1.1
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.1
      - requires==0.10.5
      - ruamel-base==1.0.0
      - soupsieve==2.7
      - sqlite-fts4==1.0.3
      - sqlite-utils==3.36
      - stack-data==0.6.3
      - tabulate==0.9.0
      - tqdm==4.66.4
      - traitlets==5.14.3
      - truststore==0.9.1
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - wcwidth==0.2.13
      - wget==3.2
      - xtyping==0.8.2
      - yaml-to-sqlite==1.0
      - zstandard==0.22.0
